name: Publish

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-20.04, macos-13, macos-12 ]
        type: [ Debug, Release ]
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure CMake
        run: |
          cmake -H. -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.type }} -DLUA_ENABLE_INSTRUMENTATION_OPT=ON

      - name: Build
        run: |
          cmake --build ${{github.workspace}}/build --config ${{ matrix.type }} --parallel $(nproc)

      - name: Test
        working-directory: ./testes
        run: |
          ${{github.workspace}}/build/bin/lua -e "_U=true" all.lua

  release:
    runs-on: ubuntu-latest
    needs: [ build ]

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true